#include "hx_drv_pmu.h"


/**
 * \enum WE1AppCfg_GPIO_e
 * \brief WE1 GPIO Selection
 */
typedef enum EMBARC_PACKED
{
	WE1AppCfg_GPIO_IOMUX_PGPIO0 = 0,
	WE1AppCfg_GPIO_IOMUX_PGPIO1,
	WE1AppCfg_GPIO_IOMUX_PGPIO2,
	WE1AppCfg_GPIO_IOMUX_PGPIO3,
	WE1AppCfg_GPIO_IOMUX_PGPIO4,
	WE1AppCfg_GPIO_IOMUX_PGPIO5,
	WE1AppCfg_GPIO_IOMUX_PGPIO6,
	WE1AppCfg_GPIO_IOMUX_PGPIO7,
	WE1AppCfg_GPIO_IOMUX_PGPIO8,
	WE1AppCfg_GPIO_IOMUX_PGPIO9,
	WE1AppCfg_GPIO_IOMUX_PGPIO10,
	WE1AppCfg_GPIO_IOMUX_PGPIO11,
	WE1AppCfg_GPIO_IOMUX_PGPIO12,
	WE1AppCfg_GPIO_IOMUX_PGPIO13,
	WE1AppCfg_GPIO_IOMUX_PGPIO14,
	WE1AppCfg_GPIO_IOMUX_RESERVED,	// reserved
	WE1AppCfg_GPIO_IOMUX_SGPIO0 = 16,
	WE1AppCfg_GPIO_IOMUX_SGPIO1,
	WE1AppCfg_GPIO_IOMUX_NONE
}HX_DRV_GPIO_IOMUX;

void print_wakeup_event(PMU_WAKEUPEVENT_E param_event);
void app_convert_wkeuppin_for_pmu_mask();
